# Task 3: Summarize the Data

Tasks based on instructions given in document https://github.com/ianmcloughlin/principles_of_data_analytics/blob/main/assessment/tasks.md

For each feature in the dataset, calculate and display:

* mean
* minimum
* maximum
* standard deviation
* median


Lets use the same Dataset as with previous tasks
* Iris Dataset 

In [ ]:
#import required modules 
import pandas as pd
import numpy as np
from sklearn import datasets as ds

#load the Iris Dataset
iris = ds.load_iris()



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

For the data summary calculation of mean/minimum/maximum/standard deviation/median.</br>
It is assumed that one should use the **numpy** mathematical operators.</br>

The 4 features that will be summarized are :
1. 'sepal length (cm)'
2.  'sepal width (cm)'
3.  'petal length (cm)'
4.  'petal width (cm)'

First use the **pandas dataframe** statistical operations ...</br>
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html

In [ ]:
# Convert Iris Dataset to DataFrame
dframe = pd.DataFrame(iris.data, columns=iris.feature_names)    #no need to add Target Column

#Extract features from dataset
for ifeature in iris['feature_names']:
    print(f'Data Summary for attribute :[{ifeature}]') #for each feature
    print(f'The Mean is : {dframe[ifeature].mean():.5f}') #print summary rounded to 5 places of decimal 
    print(f'The Minimum is : {dframe[ifeature].min():.5f}')
    print(f'The Maximum is : {dframe[ifeature].max():.5f}')
    print(f'The standard deviation is : {dframe[ifeature].std():.5f}')
    print(f'The Median is : {dframe[ifeature].median():.5f}')
    print("")
  

Data Summary for attribute :[sepal length (cm)]
The Mean is : 5.84333
The Minimum is : 4.30000
The Maximum is : 7.90000
The standard deviation is : 0.82807
The Median is : 5.80000

Data Summary for attribute :[sepal width (cm)]
The Mean is : 3.05733
The Minimum is : 2.00000
The Maximum is : 4.40000
The standard deviation is : 0.43587
The Median is : 3.00000

Data Summary for attribute :[petal length (cm)]
The Mean is : 3.75800
The Minimum is : 1.00000
The Maximum is : 6.90000
The standard deviation is : 1.76530
The Median is : 4.35000

Data Summary for attribute :[petal width (cm)]
The Mean is : 1.19933
The Minimum is : 0.10000
The Maximum is : 2.50000
The standard deviation is : 0.76224
The Median is : 1.30000



Another version that uses the numpy operations  ...</br>
https://numpy.org/doc/2.2/reference/routines.statistics.html
https://numpy.org/doc/2.2/reference/generated/numpy.mean.html#numpy.mean

*Need to convert/cast Iris Dataset to an Array then pass onto numpy.mean( )</br>
Each column is referenced with numpy slicing syntax <font color="crimson">[start:end:step]</font>*</br>

https://www.w3schools.com/python/numpy/numpy_array_slicing.asp
</br></br>
Explanation of Slicing Syntax [:, i]</br>
: (colon) represents the row slice. When placed before the comma, it means "select all rows".</br>
i is the column index, so i represents the column you want to select.</br>


In [ ]:
#Convert Iris Dataset to a numpy Array
arr_iris = np.array(iris.data)

#Extract feature columns from dataset
for i in range(arr_iris.shape[1]):
    print(f'Data Summary for attribute :{iris['feature_names'][i]}') #for each feature
    print(f'The Mean is : {np.mean(arr_iris[:,i]):.5f}') #print summary rounded to 5 places of decimal 
    print(f'The Minimum is : {np.min(arr_iris[:,i]):.5f}')
    print(f'The Maximum is : {np.max(arr_iris[:,i]):.5f}')
    print(f'The standard deviation is : {np.std(arr_iris[:,i]):.5f}')
    print(f'The Median is : {np.median(arr_iris[:,i]):.5f}')
    print("")
  

Data Summary for attribute :sepal length (cm)
The Mean is : 5.84333
The Minimum is : 4.30000
The Maximum is : 7.90000
The standard deviation is : 0.82530
The Median is : 5.80000

Data Summary for attribute :sepal width (cm)
The Mean is : 3.05733
The Minimum is : 2.00000
The Maximum is : 4.40000
The standard deviation is : 0.43441
The Median is : 3.00000

Data Summary for attribute :petal length (cm)
The Mean is : 3.75800
The Minimum is : 1.00000
The Maximum is : 6.90000
The standard deviation is : 1.75940
The Median is : 4.35000

Data Summary for attribute :petal width (cm)
The Mean is : 1.19933
The Minimum is : 0.10000
The Maximum is : 2.50000
The standard deviation is : 0.75969
The Median is : 1.30000

